### ISSUE TITLE
failed to create queue and context (and get devices)

### ISSUE THREAD

**Issue by SimonWang9610** [ProGTX/sycl-gtx#23]
I have built SYCL-GTX in my machine, but all tests that need to create `queue` by `cl::sycl::queue myQueue` or `cl::sycl::queue myQueue(device_selector)` throw `cl::sycl::exception`.
Then, I catch the exception in `try {} catch{}`, the result is `SYCL_ERROR_CODE_DOES_NOT_EXIST`. I am pretty sure the problem is due to the creation of `cl::sycl::queue`.
 I go through the source code of `queue.h` and `queue.cpp`, found all constructors of `queue` require to create `context` firstly, so I try to print messages using `debug()` in the constructors of `context`, but I did not see any message output in terminal except the same error.

If I try to create `queue` using `queue myQueue()`, it even can not pass the compilation. the error was reported as there are no member function of `queue`.

Besides, I also tried to compile those test source codes directly by `GCC` and repeated the above procedures. All of them passed compilation, but they give the same error when executing.

Maybe the problem occurs when linking `libsycl-gtx.a` with `libOpenCL.so`? Or I made some mistakes when installing `SCYL-GTX` even though I did not see any error when installing it? Or it may because the compatibility of OpenCL version and GCC version?

my test environment is:
GCC: 7.5.0
OS: Ubuntu 18.04
OpenCL version: 3.0 (Actually, `libOpenCL.so` was built when I built `DPC++` from source code, so its version is quite late.)

**Comment by SimonWang9610** [comment]
sorry, `LibOpenCL.so` is at `/usr/lcoal/cuda/lib64`, not at the directory of `DPC++`

**Comment by ProGTX** [comment]
Hi,

`SYCL_ERROR_CODE_DOES_NOT_EXIST` would indicate that you're getting a non-standard OpenCL error, possibly something specific to the device. You could try changing that in the code so that you get the actual error code, though then you'd need to figure out what the error code represents on your device.

Since you mentioned `libOpenCL.so`, maybe you need to ensure that you're using the ICD loader instead of the OpenCL implementation directly, though TBH that seems very unlikely to me to be the problem.

You also mentioned you try installing it. Does it work if you just build it and run `ctest`? It's possible something is wrong in the installation step.

Apart from that I'm not sure what the problem might be, unfortunately. I tried running it on my WSL Ubuntu 18.04 installation with Intel CPU OpenCL and it seems like it's OK-ish (6 failures, but I believe those are expected). Please note however that even though I'm happy to help with issues you might face, this project is not actively maintained.
